# Generated by Django 5.2.5 on 2025-09-02 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=64, unique=True)),
                ('friendly_name', models.CharField(default='', max_length=128)),
                ('provider', models.CharField(default='OpenAI', max_length=32)),
                ('model_name', models.CharField(max_length=128)),
                ('pricing_mode', models.CharField(choices=[('text', 'text'), ('image', 'image')], default='text', max_length=8)),
                ('input_per_million_usd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('output_per_million_usd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cached_per_million_usd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('per_image_input_usd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('per_image_output_usd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_per_month', models.BigIntegerField(default=1000000)),
                ('active', models.BooleanField(default=True)),
                ('renew_day', models.PositiveSmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_tokens', models.BigIntegerField()),
                ('reason', models.CharField(max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_alias', models.CharField(max_length=64)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_tokens', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
