# Generated by Django 5.2.5 on 2025-09-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient'), ('both', 'both')], default='patient', max_length=16),
        ),
    ]
